# Based on blas metapackage: https://github.com/conda-forge/blas-feedstock
# Some useful notes can be found at https://conda-forge.hackpad.com/BLAS-Numpy-Friends-86De62hoNdT
# See discussion: https://github.com/conda-forge/staged-recipes/pull/1501

# The version should be in the form X.Y[.z], where X denotes major infrastructural change to how mpi is managed,
# and Y denoting mpi priority. Having MPI priority causes `conda upgrade --all` to switch to preferred provider,
# so currently express no priority.
# .z can be incremented for fully compatible changes
{% set Y = 0 %}
package:
  name: mpi
  version: 1.{{ Y }}.0

build:
  # We mustn't use the build number in the mpi package - because we are defining the string,
  # manually we would not be producing unique filenames.
  number: 0
  string: {{ mpi }}
  noarch: generic

requirements: {}
  # None, mpi providers should depend on me

test:
  commands:
    - echo "I'm a metapackage"

about:
  home: https://github.com/conda-forge/mpi-feedstock
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE.txt
  summary: Metapackage to select the MPI variant. Use conda's pinning mechanism in your environment to control which variant you want.

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - leofang
